name: Build LaTeX document
on:
  push:
    branches:
      - feature/latex_resume
      - main
    paths:
      - "resume/*"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume/resume.tex

      - name: Commit PDF LaTeX resume
        run: |
          git config --global user.name "mtouzot"
          git config --global user.email "mtouzot@users.noreply.github.com"
          git add resume.pdf
          git commit -m "Upload PDF resume"
          git push
  